### ISSUE TITLE
Wont run

### ISSUE THREAD

**Issue by TriTriTheCuber** [DXVVAY/nexus#2]
I used setup.bat then start.bat when it finished installing and i did not see anything. Yes, i have python.

**Comment by TriTriTheCuber** [comment]
![Screenshot 2024-02-11 123838](https://github.com/DXVVAY/nexus/assets/121834111/5518430b-376d-4f33-b5fb-e4360514494c)
Also i got This error on the install

**Comment by TriTriTheCuber** [comment]
and got this error using cmd to run main.py
![Screenshot 2024-02-11 123948](https://github.com/DXVVAY/nexus/assets/121834111/4be0df4f-990f-4212-994a-ab0ca5879ec7)

**Comment by DXVVAY** [comment]
pip install (missing module)
